package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	l "github.com/SisyphusSQ/summary-sys/pkg/log"
	"github.com/SisyphusSQ/summary-sys/vars"
)

var (
	debug     bool
	logOutput string
	logFile   string
)

const forceStderrAnnotationKey = "force-stderr"

var rootCmd = &cobra.Command{
	Use:   vars.AppName,
	Short: "summary-sys CLI",
	Long:  "summary-sys is generated by go-cli-starter.",
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		mode, err := parseOutputMode(logOutput)
		if err != nil {
			return err
		}
		if shouldForceStderr(cmd) {
			mode = l.OutputStderr
		}

		if err := l.New(debug, mode, logFile); err != nil {
			return fmt.Errorf("init logger: %w", err)
		}
		l.Logger.Debugf("logger initialized, mode=%s", mode)

		return nil
	},
	PersistentPostRun: func(cmd *cobra.Command, args []string) {
		if l.Logger != nil {
			l.Logger.Sync()
		}
	},
	Run: func(cmd *cobra.Command, args []string) {
		_ = cmd.Help()
	},
}

func registerBaseFlags(cmd *cobra.Command) {
	cmd.PersistentFlags().BoolVar(&debug, "debug", false, "Enable debug logging")
	cmd.PersistentFlags().StringVar(
		&logOutput,
		"log-output",
		"stdio",
		"Log output target: stdio | stderr | file",
	)
	cmd.PersistentFlags().StringVar(
		&logFile,
		"log-file",
		fmt.Sprintf("./logs/%s.log", vars.AppName),
		"Log file path used when --log-output=file",
	)
}

func parseOutputMode(value string) (l.OutputMode, error) {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "stdio":
		return l.OutputStdio, nil
	case "stderr":
		return l.OutputStderr, nil
	case "file":
		return l.OutputFile, nil
	default:
		return l.OutputStdio, fmt.Errorf(
			"invalid --log-output: %s (allowed: stdio, stderr, file)",
			value,
		)
	}
}

func shouldForceStderr(cmd *cobra.Command) bool {
	for c := cmd; c != nil; c = c.Parent() {
		if c.Annotations != nil && c.Annotations[forceStderrAnnotationKey] == "true" {
			return true
		}
	}

	return false
}

func initAll() {
	initVersion()
	initMCP()
}

func Execute() {
	registerBaseFlags(rootCmd)
	initAll()
	rootCmd.SilenceErrors = true

	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
